# EmojiTab Configuration
# Plugin for tab-completing emojis and unicode characters in Minecraft 1.21.4+

# Character(s) to wrap around emoji shortcodes
# Examples: ":" for :cloud:, "" for cloud, "~" for ~cloud~
emoji-wrapping: ":"

# Whether to require the emoji.use permission to use emojis
# If false, all players can use emojis
use-permissions: false

# Whether to require individual permissions for each emoji
# If true, players need emoji.use.<emoji_name> permission for each emoji
# Example: emoji.use.cloud, emoji.use.heart, etc.
individual-permissions: false

# Whether to show detailed emoji loading information in console
verbose: false

# Custom skin for fake players in tab list
# Get texture data from https://mineskin.org
# Leave blank to use the default gray skin
custom-texture-data: ""
custom-texture-signature: ""

# Plugin behavior settings
settings:
  # Maximum number of emojis to show in tab completion at once
  max-tab-suggestions: 50
  
  # Whether to sort emojis alphabetically in tab completion
  sort-alphabetically: true
  
  # Whether to show emoji character in tab list alongside shortcode
  show-character-in-tab: true
