name: EmojiTab
version: ${project.version}
main: com.github.remynfv.emojitab.EmojiTab
api-version: 1.17
authors: [ Legitimoose ]
description: A plugin for tab completing emojis!
website: youtube.com/legitimoose
