name: EmojiTab
version: ${project.version}
main: com.github.remynfv.emojitab.EmojiTab
api-version: 1.17
authors: [ Legitimoose ]
description: A plugin for tab completing emojis!
website: https://youtube.com/legitimoose
depend: [ProtocolLib]
commands:
  emoji:
    #TODO Write description
    aliases:
      - emojis
    description: /emoji
    usage: /emoji [list,reload,toggle]