name: EmojiTab
version: ${project.version}
main: com.github.remynfv.emojitab.EmojiTab
api-version: 1.17
authors: [ Legitimoose ]
description: A plugin for tab completing emojis!
website: youtube.com/legitimoose
depend: [ProtocolLib]
commands:
  test:
    description: Test command *world explodes*
    usage: /test
  emoji:
    #TODO Write description
    description: /emoji
    usage: /emoji [list,reload,toggle]