name: EmojiTab
version: ${project.version}
main: com.github.remynfv.emojitab.EmojiTab
api-version: 1.19
authors: [ Legitimoose ]
description: A plugin for tab completing emojis!
website: https://youtube.com/legitimoose
depend: [ProtocolLib]
commands:
  emoji:
    description: Shows list of emojis.
    usage: /emoji [list|reload|toggle]